name: Test

on:
  push:
    branches:
      - master
      - ghworkflow
  pull_request:
    branches:
      - master

jobs:

  linux:
    strategy:
      matrix:
        go: ["1.23", "1.24", "1.25"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.go }}"

      - run: go test ./...
      - run: go vet ./...
      - run: cd test; ./test.sh

  linux-32bit:
    strategy:
      matrix:
        go: ["1.23"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.go }}"

      - run: go test ./...

  darwin:
    strategy:
      matrix:
        go: ["1.23"]
    runs-on: macos-15
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.go }}"

      - run: go test ./...

  linux-stress:
    strategy:
      matrix:
        go: ["1.23"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "${{ matrix.go }}"

      - run: go install github.com/cockroachdb/stress@latest
      - run: go test ./... -exec 'stress -p 2 -maxruns 10' -v